import React, { useEffect, useState } from "react";
import axios from "axios";
import { useQuill } from "react-quilljs";
import "quill/dist/quill.snow.css";
import { useNavigate } from "react-router";
import { Alert } from "@mui/material";
import Spinner from "../../components/Spinner.jsx";

const EditorPage = ({ summary, id }) => {
  const { quill, quillRef } = useQuill();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const initialContent = summary;

        if (quill) {
          quill.clipboard.dangerouslyPasteHTML(initialContent);
        }
      } catch (error) {
        console.error("Error fetching content:", error);
      }
    };

    fetchData();
  }, [quill, summary]);

  const handleSave = async () => {
    try {
      setLoading(true);

      if (!quill) {
        console.error("Quill is not available");
        return;
      }

      const newContent = quill.root.innerHTML;
      const response = await axios.post(
        `http://localhost:8000/api/v1/video/pdf/${id}`,
        {
          content: newContent,
        }
      );

      if (response.status === 201) {
        navigate("/");
        console.log("Content saved successfully: ");
      }
    } catch (error) {
      console.error("Error saving content:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-2 w-[98%] md:w-[85%] lg:w-3/4 mx-auto">
      {loading ? (
        <Spinner />
      ) : (
        <>
          <Alert severity="info" className="my-6 w-full lg:w-[80%]">
            Disclaimer: This content has been generated by AI. Feel free to edit
            and customize it according to your preferences.
          </Alert>
          <div className="text-center">
            <div
              ref={quillRef}
              className="h-[500px] bg-gray-200 shadow-lg rounded-md"
            ></div>
            <button
              className="bg-blue-500 text-white rounded-md px-4 py-2 my-4"
              onClick={handleSave}
            >
              Save
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default EditorPage;
